language: python
python:
  - "2.6"
  - "2.7"
services:
  - elasticsearch
  - postgresql
env:
  global:
    - DJANGO_DEBUG=1
    - UPLOADCARE_DISABLED=1
    - ROLLBAR_DISABLED=1
    - DJANGO_SECRET_KEY=foo
    - DATABASE_URL=postgres://travis@127.0.0.1/travis_ci_test
    - HOSTNAMES=localhost
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
script:
  - python manage.py test pylinks
